server:
  port: 8802
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    # Since it does not support multiple localhost Eureka servers, but there is only a local test environment, you can only customize the host name.
    # Change the host name to eureka01
    hostname: eureka02
  client:
    fetch-registry: false
    # Remove the register-with-eureka option and let the Eureka server register itself to other Eureka servers so that they can enable each other.
    service-url:
      # Note that you need to fill in the addresses of other Eureka servers here. You don’t need to write your own.
      defaultZone: http://eureka01:8801/eureka