#server:
#  port: 8101
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.190.128:3306/cloudstudy
#    username: root
#    password: 123
#  # application name bookservice
  application:
    name: book-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
    nacos:
      discovery:
        # Nacos configuration
        server-addr: localhost:8848
        # namespace will apart from others
        namespace: 4f951b28-e2e2-46d6-9c2b-448fd33895dc
    loadbalancer:
      nacos:
        enabled: true
seata:
  # register
  registry:
    # Use Nacos
    type: nacos
    nacos:
      # Use the Seata namespace so that the Seata service can be found correctly. Since the group uses SEATA_GROUP, the default configuration value is, so there is no need to configure it.
      namespace: b13a353e-a2c5-45cb-8e6f-c231ee7f5f27
      username: nacos
      password: nacos
  #Configuration
  config:
    type: nacos
    nacos:
      namespace: b13a353e-a2c5-45cb-8e6f-c231ee7f5f27
      username: nacos
      password: nacos


